# Generated by Django 5.2 on 2025-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehiculo_activo_vehiculo_año_vehiculo_kilometraje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
