# Generated by Django 5.2 on 2025-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehiculo_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='seguro_empresa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
