# Generated by Django 5.2 on 2025-04-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehiculo_seguro_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='titular_cabify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_cabify', to='core.chofer'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='titular_uber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_uber', to='core.chofer'),
        ),
    ]
