# Generated by Django 5.2 on 2025-04-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehiculo_titular_cabify_vehiculo_titular_uber'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='beneficiario_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos_recibidos', to='core.chofer'),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='es_titular',
            field=models.BooleanField(default=False),
        ),
    ]
