# Generated by Django 5.2 on 2025-04-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_es_titular_rendicion_cerrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='es_titular',
        ),
    ]
